baseURL = 'https://sinanthahir.github.io'
languageCode = 'en-us'
title = 'Sin(x)'
theme = "hugo-theme-monochrome"
disqusShortname = 'sinx-1'

[build]
    writeStats = true

[taxonomies]
    category = "categories"
    tags = "tags"
    series = "series"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    favicon = "/img/favicon.ico"
    footer = "Sinan Thahir Â© 2022"
    enableZoomingJS = true
    enableTOC = false
    enableSiteSearch = true
    enableMathJax = false
    # Codeblock
    usePrismJS = false
    enablePrismJSLineNo = true
    enableCodeCopy = true
    # SEO
    enableOpenGraph = true
    enableTwitterCards = true
    author = "sinan"
    # Collapsible Menu
    enableCollapsibleTOC = false
    enableCollapsibleChangelogs = true

[goldmark.renderer]
unsafe= true

[highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[[navbar]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
[[navbar]]
    identifier = "timeline"
    name = "Timeline"
    url = "/timeline/"
    weight = 2
[[navbar]]
    identifier = "bookshelf"
    name = "Bookshelf"
    url = "/bookshelf/"
    weight = 3
[[navbar]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase/"
    weight = 4
[[navbar]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 5
[[navbar]]
    identifier = "nerd-stuff"
    name = "Nerd Stuff"
    url = "/nerd-stuff"
    weight = 6